using ASAPPVC.UI.Models.Enums;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASAPPVC.UI.Models
{
    [Index(nameof(ComponentCode), IsUnique = true)]
    public class Component
    {
        // Internal GUID primary key for safe relations
        [Key]
        public Guid Id { get; set; } = Guid.NewGuid();

        // Human-friendly public code (generated by CodeGenerator if not provided)
        [Required]
        [MaxLength(64)]
        public string ComponentCode { get; set; } = string.Empty;

        [Required]
        [MaxLength(100)]
        public string Name { get; set; } = string.Empty;

        [Required]
        public Unit Unit { get; set; } = Unit.Piece;

        [Required]
        [Column(TypeName = "decimal(18,2)")]
        public decimal UnitCost { get; set; }

        [Required]
        [Range(0, int.MaxValue, ErrorMessage = "Current amount cannot be negative")]
        public int CurrentAmount { get; set; }

        [Required]
        [MaxLength(50)]
        public string StorageLocation { get; set; } = string.Empty;

        // Optional image data
        public byte[] ImageData { get; set; } = Array.Empty<byte>();

        [MaxLength(50)]
        public string ImageType { get; set; } = string.Empty;

        // Optional reverse nav: allows counting usage for detail screens
        public ICollection<ProductComponent>? ProductComponents { get; set; }
    }
}