using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASAPPVC.UI.Models
{
    [Index(nameof(PartCode), IsUnique = true)]
    public class PartModel
    {
        // Internal GUID primary key for safe relations
        [Key]
        public Guid Id { get; set; } = Guid.NewGuid();

        // Human-friendly public code (generated by CodeGenerator)
        [Required]
        [MaxLength(64)]
        public string PartCode { get; set; } = string.Empty;

        [Required]
        [MaxLength(100)]
        public string Name { get; set; } = string.Empty;

        [Required]
        [Column(TypeName = "decimal(18,2)")]
        public decimal UnitCost { get; set; }

        [Required]
        [Range(0, int.MaxValue, ErrorMessage = "Current amount cannot be negative")]
        public int CurrentAmount { get; set; }

        [Required]
        [MaxLength(50)]
        public string StorageLocation { get; set; } = string.Empty;

        // Optional image data
        public byte[]? ImageBytes { get; set; }

        public string? ImageContentType { get; set; }
    }
}